Repository chingu-voyages/v11-bears-team-10, pull requests merged in 2019-09, with the labels that each got.

#28 refactored redux skeleton folder structure to be able to detect new r…
  client/.vs/VSWorkspaceState.json
  client/.vs/client/v15/.suo
  client/.vs/slnx.sqlite
  client/package-lock.json
  client/src/App.css
  client/src/App.js
  client/src/index.css
  client/src/index.js
  client/src/redux/middlewares/index.js
  client/src/redux/middlewares/logger.js
  client/src/redux/reducers/anotherTestReducer.js
  client/src/redux/reducers/index.js
  client/src/redux/reducers/testReducerData.js
  client/src/redux/store.js
  client/src/store/store.js
Labels: type: frontend

#26 closes #23
  client/.vs/VSWorkspaceState.json
  client/.vs/client/v15/.suo
  client/.vs/slnx.sqlite
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.js
  client/src/index.css
  client/src/index.js
  client/src/logo.svg
  client/src/redux/middlewares/index.js
  client/src/redux/middlewares/logger.js
  client/src/redux/reducers/anotherTestReducer.js
  client/src/redux/reducers/index.js
  client/src/redux/reducers/testReducerData.js
  client/src/redux/store.js
  client/yarn.lock
Labels: type: frontend

#24 added user schema
  server/models/project.js
  server/models/user.js
Labels: type: backend

#31 fixes #30
  client/.vs/VSWorkspaceState.json
  client/.vs/client/v15/.suo
  client/.vs/slnx.sqlite
  client/src/App.js
  client/src/DashBoard.js
  client/src/ErrorInfo.js
  client/src/HomePage.js
  client/src/LoginForm.js
  client/src/RegisterForm.js
  client/src/index.js
  client/src/navbar/NavBar.js
  client/src/navbar/ProfileDropdown.js
  client/src/redux/actionCreators.js
Labels: duplicate

#29 basic react router implementation
  client/.vs/VSWorkspaceState.json
  client/.vs/client/v15/.suo
  client/.vs/slnx.sqlite
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/DashBoard.js
  client/src/ErrorInfo.js
  client/src/HomePage.js
  client/src/LoginForm.js
  client/src/RegisterForm.js
  client/src/index.js
  client/src/index.scss
  client/src/navbar/NavBar.js
  client/src/navbar/ProfileDropdown.js
  client/src/redux/actionCreators.js
  client/src/redux/reducers/anotherTestReducer.js
  client/src/redux/reducers/errorReducer.js
  client/src/redux/reducers/testReducerData.js
  client/src/redux/reducers/userReducer.js
Labels: type: frontend

#38 closes #8 and #37
  client/package.json
  client/src/DashBoard.js
  client/src/components/Card/AddProjectCard.js
  client/src/components/Card/Card.js
  client/src/index.js
  client/src/stylesheets/components/_card.scss
  client/src/stylesheets/components/_dashboard.scss
  client/src/stylesheets/css/styles.css
  client/src/stylesheets/helpers/_mixins.scss
  client/yarn.lock
Labels: type: frontend

#39 closes #9
  client/src/DashBoard.js
  client/src/components/Card/AddProjectCard.js
  client/src/components/Card/Card.js
  client/src/container/Modals/AddProjectForm.js
  client/src/images/greenbrand.png
  client/src/index.js
  client/src/stylesheets/components/_addProject.scss
  client/src/stylesheets/components/_dashboard.scss
  client/src/stylesheets/css/styles.css
  client/src/stylesheets/helpers/_mixins.scss
  client/src/stylesheets/helpers/_variables.scss
  client/src/stylesheets/main.scss
Labels: type: frontend

#41 Ft enhance dashboard
  client/src/DashBoard.js
  client/src/components/Header/Header.js
  client/src/components/ProjectBoard/ProjectBoard.js
  client/src/index.js
  client/src/stylesheets/components/_dashboard.scss
  client/src/stylesheets/components/_header.scss
  client/src/stylesheets/main.scss
Labels: enhancement

#49 closes #48
  client/src/components/ProjectBoard/ProjectBoard.js
  client/src/components/TodoList/TodoList.js
  client/src/images/icons/icons.js
  client/src/index.js
  client/src/stylesheets/components/_dashboard.scss
  client/src/stylesheets/components/_projectboard.scss
  client/src/stylesheets/components/_todolist.scss
  client/src/stylesheets/helpers/_mixins.scss
  client/src/stylesheets/helpers/_variables.scss
  client/src/stylesheets/main.scss
Labels: type: frontend

#51 closes #50
  client/src/components/Messages/Message.js
  client/src/components/Messages/MessageBoard.js
  client/src/components/ProjectBoard/ProjectBoard.js
  client/src/components/Todos/TodoList/TodoList.js
  client/src/components/Todos/TodosBoard/TodosBoard.js
  client/src/stylesheets/components/_message.scss
  client/src/stylesheets/components/_todolist.scss
  client/src/stylesheets/main.scss
Labels: type: frontend

#52 fix client side bug
  client/src/components/Card/AddProjectCard.js
  client/src/components/Dashboard.js
  client/src/components/Header/Header.js
  client/src/components/ProjectBoard/ProjectBoard.js
  client/src/container/Modals/AddProjectForm.js
  client/src/index.js
  client/src/stylesheets/components/_card.scss
  client/src/stylesheets/components/_dashboard.scss
  client/src/stylesheets/components/_projectboard.scss
  client/src/stylesheets/components/_todolist.scss
  client/src/stylesheets/css/styles.css
  client/src/stylesheets/main.scss
Labels: bug, type: frontend

#57 closes #56
  client/package.json
  client/public/index.html
  client/src/components/Messages/MessageBoard.js
  client/src/components/ProjectBoard/ProjectBoard.js
  client/src/components/Todos/AddTodo.js
  client/src/components/Todos/TodoList/TodoList.js
  client/src/components/Todos/TodoPortal.js
  client/src/components/Todos/Todos.js
  client/src/components/Todos/TodosBoard/TodosBoard.js
  client/src/container/Modals/AddProjectForm.js
  client/src/images/icons/icons.js
  client/src/index.js
  client/src/stylesheets/components/_addProject.scss
  client/src/stylesheets/components/_addTodo.scss
  client/src/stylesheets/components/_dashboard.scss
  client/src/stylesheets/components/_projectboard.scss
  client/src/stylesheets/components/_todolist.scss
  client/src/stylesheets/components/_todos.scss
  client/src/stylesheets/helpers/_mixins.scss
  client/src/stylesheets/main.scss
  client/yarn.lock
Labels: type: frontend

#59 closes #58
  client/src/HOC/portal/portal.js
  client/src/components/Dashboard.js
  client/src/components/Header/Header.js
  client/src/components/Messages/AddMessageList.js
  client/src/components/Messages/Message.js
  client/src/components/Messages/MessageBoard.js
  client/src/components/Messages/MessageList/MessageList.js
  client/src/components/Todos/AddTodoList.js
  client/src/components/Todos/TodoList/TodoList.js
  client/src/components/Todos/TodoPortal.js
  client/src/components/Todos/Todos.js
  client/src/components/Todos/TodosBoard/TodosBoard.js
  client/src/index.scss
  client/src/stylesheets/components/_header.scss
  client/src/stylesheets/components/_todos.scss
Labels: type: frontend

#62 closes #61
  client/src/components/Dashboard.js
  client/src/components/Footer/Footer.js
  client/src/components/ProjectBoard/ProjectBoard.js
  client/src/index.js
  client/src/index.scss
  client/src/stylesheets/components/_dashboard.scss
  client/src/stylesheets/components/_footer.scss
  client/src/stylesheets/components/_header.scss
  client/src/stylesheets/components/_projectboard.scss
  client/src/stylesheets/main.scss
Labels: type: frontend

#65 closes #64
  client/src/App.js
  client/src/components/Dashboard.js
  client/src/components/LandingPage.js
  client/src/components/ProjectBoard/ProjectBoard.js
  client/src/images/landing.png
  client/src/stylesheets/components/_landingPage.scss
  client/src/stylesheets/helpers/_mixins.scss
  client/src/stylesheets/main.scss
  client/yarn.lock
  server/yarn.lock
Labels: type: frontend

#67 closes #66
  client/src/navbar/AuthenticationButtons.js
  client/src/navbar/NavBar.js
  client/src/stylesheets/components/_footer.scss
  client/src/stylesheets/components/_landingPage.scss
  client/src/stylesheets/components/_navbar.scss
  client/src/stylesheets/helpers/_mixins.scss
  client/src/stylesheets/main.scss
Labels: type: frontend

#69 closes #68
  client/package.json
  client/src/components/Card/ProjectCard.js
  client/src/components/Dashboard.js
  client/src/container/Modals/AddProjectForm.js
  client/src/images/icons/icons.js
  client/src/index.js
  client/src/redux/action_creators/project.js
  client/src/redux/reducers/project.js
  client/src/redux/reducers/userReducer.js
  server/controllers/project.js
  server/passport/index.js
  yarn.lock
Labels: type: frontend

#71 closes #70
  client/src/App.js
  client/src/components/Card/ProjectCard.js
  client/src/components/Dashboard.js
  client/src/components/ProjectBoard/ProjectBoard.js
  client/src/redux/action_creators/project.js
  client/src/redux/reducers/project.js
  client/src/stylesheets/components/_card.scss
  server/controllers/project.js
Labels: type: frontend

#72 client delete project
  client/src/components/Card/ProjectCard.js
  client/src/redux/action_creators/project.js
  client/src/redux/reducers/project.js
Labels: bug, type: frontend

#73 re-arrange dashboard folders
  client/src/components/Dashboard.js
  client/src/components/ProjectBoard/ProjectBoard.js
  client/src/components/Todos/AddTodoForm.js
  client/src/components/Todos/TodoView.js
  client/src/components/Todos/Todos/Todo.js
  client/src/components/Todos/TodosBoard/TodosBoard.js
  client/src/redux/action_creators/project.js
  client/src/redux/reducers/project.js
  server/controllers/project.js
  server/routes/project.js
Labels: type: frontend

#74 update dashboard logic
  client/src/components/Dashboard.js
  client/src/components/ProjectBoard/ProjectBoard.js
  client/src/container/Modals/AddProjectForm.js
  client/src/redux/reducers/project.js
  client/src/stylesheets/components/_card.scss
  client/src/stylesheets/components/_dashboard.scss
  client/src/stylesheets/components/_projectboard.scss
Labels: type: frontend

#75 fix add/delete client logic
  client/src/components/Dashboard.js
  client/src/container/Modals/AddProjectForm.js
  client/src/redux/action_creators/project.js
  client/src/redux/action_creators/user.js
  client/src/redux/reducers/project.js
  client/src/redux/reducers/userReducer.js
Labels: bug, type: frontend

#76 fix view-project
  client/src/components/Card/ProjectCard.js
  client/src/components/Dashboard.js
  client/src/components/ProjectBoard/ProjectBoard.js
  client/src/components/Todos/AddTodoForm.js
  client/src/components/Todos/TodosBoard/TodosBoard.js
  client/src/redux/action_creators/project.js
  client/src/stylesheets/components/_projectboard.scss
Labels: type: frontend

#77 Update action creators
  client/src/components/ProjectBoard/ProjectBoard.js
  client/src/components/Todos/AddTodoForm.js
  client/src/redux/action_creators/project.js
  client/src/redux/action_creators/user.js
Labels: enhancement, type: frontend

#78 fix folders - client
  client/src/App.js
  client/src/components/Dashboard.js
  client/src/components/Projects/AddProjectForm.js
  client/src/components/Projects/Card/AddProjectCard.js
  client/src/components/Projects/Card/ProjectCard.js
  client/src/components/Projects/ProjectBoard/ProjectBoard.js
  client/src/components/Todos/AddTodoForm.js
  client/src/redux/action_creators/project.js
  client/src/stylesheets/components/_projectboard.scss
Labels: type: frontend
